name: Auto PR test

on:
  pull_request:
    branches: main
    types: [closed]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v2

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: develop
          pr_title: Merge ${{ github.base_ref }} into develop
          pr_body: "#${{ github.event.pull_request.number }}"
          pr_assignee: eduidl
          pr_label: auto-pr
          github_token: ${{ secrets.GITHUB_TOKEN }}
